require("mothership.plugins-setup")
require("mothership.core.options")
require("mothership.core.keymaps")
require("mothership.core.colorscheme")
require("mothership.plugins.nvim-tree")
require("mothership.plugins.lualine")
local async = require "plenary.async" -- used like this because telescope is dependant on it & other method didn't work.
require("mothership.plugins.telescope")
require("mothership.plugins.nvim-cmp")
require("mothership.plugins.lsp.mason")
require("mothership.plugins.lsp.lspsaga")
require("mothership.plugins.lsp.lspconfig")
require("mothership.plugins.colorizer")
require("mothership.plugins.gitsigns")
require("mothership.plugins.autopairs")
vim.cmd('set clipboard+=unnamedplus')
